spring:
  datasource:
    url: jdbc:postgresql://postgres:5432/${POSTGRES_DB}
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
    driver-class-name: org.postgresql.Driver
  cloud:
    nacos:
      discovery:
        service: ${spring.application.name}
        server-addr: nacos:8848
      config:
        server-addr: nacos:9848
        file-extension: yaml
        group: DEFAULT_GROUP
        import-check:
          enabled: false
  data:
    redis:
      host: redis
      port: 6379
      password: ${REDIS_PASSWORD}
      database: 2

dubbo:
  application:
    name: ${spring.application.name}-dubbo
    qos-enable: false
  registry:
    address: nacos://${spring.cloud.nacos.discovery.server-addr}
    register-mode: instance
  consumer:
    timeout: 3000
    check: false
  protocol:
    name: dubbo
    port: -1

gateway:
  port: 75