server:
  port: 75 # 网关端口

spring:
  main:
    web-application-type: reactive # 响应式编程模型
  application:
    name: gateway
  thymeleaf:
    cache: true # 缓存 index.html
  # redis 配置
  data:
    redis:
      host: localhost
      port: 6379
      # password 在程序实参中添加redis的密码
      database: 1
      lettuce:
        pool:
          max-idle: 128 # 最大空闲连接数
          max-active: 256 # 最大活跃连接数
          min-idle: 64 # 最小空闲连接数
          max-wait: 100ms # 最大等待时间

  cloud:
    nacos: # 使用nacos作为注册中心
      discovery:
        server-addr: 127.0.0.1:8848
    gateway:
      server:
        webflux:
          routes:
            # 此配置用于将 Path 的第一部分去除
            # 如果请求路径是 /users/xxx，经过 StripPrefix 过滤器后，路径会变成 /xxx。
            # 即微服务中接收到的请求为 /xxx
            # filters:
            #   - name: StripPrefix
            #     args:
            #       parts: 1

            # 用户服务
            - id: user-service
              uri: lb://user-service # http://localhost:8100
              predicates:
                - Path=/users/**
              filters:
                - name: StripPrefix
                  args:
                    parts: 1

            # 邮件服务
            - id: mail-service
              uri: lb://mail-service # http://localhost:8101
              predicates:
                - Path=/mail/**
              filters:
                - name: StripPrefix
                  args:
                    parts: 1

            # 文件上传服务
            - id: upload-service
              uri: lb://upload-service # http://localhost:8102
              predicates:
                - Path=/fu/**
              filters:
                - name: StripPrefix
                  args:
                    parts: 1

            # 文件下载服务
            - id: download-service
              uri: lb://download-service # http://localhost:8103
              predicates:
                - Path=/fd/**
              filters:
                - name: StripPrefix
                  args:
                    parts: 1

            # 文件系统服务
            - id: file-system
              uri: lb://file-system # http://localhost:8104
              predicates:
                - Path=/fs/**
              filters:
                - name: StripPrefix
                  args:
                    parts: 1

logging:
  level:
    root: INFO
